k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 10000
    sinceSeconds: 300
    fullScreenLogs: true
    textWrap: false
    showTime: true
  ui:
    skin: everforest-dark
  keepMissingClusters: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  disablePodCounting: false
